title: AutoScaler
email: caf@hpe.com

description: AutoScaler Description
#baseurl: "/documentation"
baseurl: "https://autoscaler.github.io/autoscaler"

# Build settings
exclude: ['node_modules']

markdown: kramdown
highlighter: rouge

gems: ['jekyll-coffeescript', 'jekyll-watch', 'jekyll-assets', 'jekyll-paginate']

layouts_dir:  caf-templates/_layouts
includes_dir: caf-templates/_includes
sass:
    sass_dir: caf-templates/_sass

paginate: 5
paginate_path: "/pages/en-us/blog/page:num/"
