apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-deployment
  labels:
    app: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
        - name: autoscaler
          image: dev/autoscaler/autoscale-kubernetes-rabbit:1.9.0-SNAPSHOT
          ports:
            - containerPort: 80
          env:
            - name: CAF_RABBITMQ_MGMT_URL
              value: "http://mu-rabbit-rabbitmq.rabbit:15672"
            - name: CAF_RABBITMQ_MGMT_USERNAME
              value: "user"
            - name: CAF_RABBITMQ_MGMT_PASSWORD
              value: "xwSYg2JOBa"
            - name: CAF_AUTOSCALER_KUBERNETES_NAMESPACES
              value: "default,test"
