version: '3'
services:
  autoscaler:
    env_file:
      - ./rabbitmq.env
    environment:
      DOCKER_HOST: ${DOCKER_HOST:-<DOCKER_HOST_HERE_PLEASE_SET>}
      CAF_AUTOSCALER_DOCKER_SWARM_STACK: ${CAF_AUTOSCALER_DOCKER_SWARM_STACK:-autoscalerdemo}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    image: autoscaler/autoscale-dockerswarm-rabbit:{project.version}
    ports:
      - "${AUTOSCALER_PORT:-9981}:8081"
